name: flutter_axtro_soft_ecommerce
description: A new Flutter setup application for starting a project.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre
  firebase_core_platform_interface: ^4.5.1

  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  provider: ^6.0.5
  connectivity: ^3.0.6
  dio: ^5.1.2 
  http: ^0.13.6
  freezed: ^2.3.4
  shared_preferences: ^2.1.1
  fancy_bottom_navigation: ^0.3.3
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.4.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.11
  image_picker: ^0.8.7+5
  #need edit
  webview_flutter: ^3.0.0
  flutter_html: ^2.2.1
  share: ^2.0.4
  photo_view: ^0.14.0
  package_info: ^2.0.2
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.1
  flutter_local_notifications: ^14.1.0
  path_provider: ^2.0.15
  google_sign_in: ^6.1.2 #note
  flutter_facebook_auth: ^5.0.11
  flutter_svg: ^1.1.6
  phone_number: ^1.0.0
  country_code_picker: ^2.0.0
  pin_code_fields: ^7.4.0
  google_maps_flutter: ^2.2.8
  flutter_google_places: ^0.3.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  flutter_typeahead: ^4.4.0
  marquee: ^2.2.3
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html: ^0.8.0
  flutter_widget_from_html_core: ^0.6.0
  flutter_html_table: ^3.0.0-alpha.2
  fluttertoast: ^8.2.2
  permission_handler: ^10.2.0
  flutter_downloader: ^1.6.1
  country_currency_pickers: ^3.0.0
  dropdown_search: ^5.0.6





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 600
